ARG IMAGE=php:8.1-fpm-alpine
FROM ${IMAGE} AS build

COPY ./src/web /web
RUN set -eux; \
    chown -R www-data:www-data /web; \
    find /web -type d -exec chmod 750 {} \;; \
    find /web -type f -exec chmod 640 {} \;;

COPY ./src/heatmaps /heatmaps
RUN set -eux; \
    chown -R www-data:www-data /heatmaps; \
    find /heatmaps -type d -exec chmod 750 {} \;; \
    find /heatmaps -type f -exec chmod 640 {} \;;

FROM ${IMAGE} AS base

RUN set -eux; \
    apk add --no-cache ca-certificates nginx supervisor; \
    docker-php-ext-install opcache mysqli pdo pdo_mysql; \
    apk add --no-cache freetype libjpeg-turbo libpng; \
    apk add --no-cache --virtual .deps freetype-dev libjpeg-turbo-dev libpng-dev; \
    docker-php-ext-configure gd --with-freetype=/usr/include/ --with-jpeg=/usr/include/; \
    docker-php-ext-install gd; \
    apk del .deps; \
    apk add --no-cache --virtual .deps linux-headers; \
    docker-php-ext-install sockets; \
    apk del .deps

COPY ./config/web/. /

RUN set -eux; \
    mv -v /usr/local/etc/php-fpm.d/docker.conf /usr/local/etc/php-fpm.d/docker.conf.disabled; \
    mv -v /usr/local/etc/php-fpm.d/www.conf /usr/local/etc/php-fpm.d/www.conf.disabled; \
    mv -v /usr/local/etc/php-fpm.d/zz-docker.conf /usr/local/etc/php-fpm.d/zz-docker.conf.disabled

COPY --from=build /web /web
COPY --from=build /heatmaps /heatmaps

WORKDIR /web
CMD ["/usr/bin/supervisord", "-c", "/supervisor.conf", "--pidfile", "/run/supervisord.pid"]

FROM base AS dev

RUN set -eux; \
    apk add --no-cache --virtual .build-dependencies $PHPIZE_DEPS; \
    if pecl install xdebug; then \
      docker-php-ext-enable xdebug; \
      { \
          echo "[xdebug]"; \
          echo "zend_extension=xdebug"; \
          echo "xdebug.mode=debug"; \
          echo "xdebug.start_with_request=yes"; \
          echo "xdebug.client_host=host.docker.internal"; \
          echo "xdebug.client_port=9000"; \
      } > /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini; \
    else \
      echo "WARNING: unable to install xdebug, continuing without it"; \
    fi; \
    docker-php-source delete || true; \
    apk del .build-dependencies

FROM base AS prod
