FROM alpine:latest AS build

RUN set -eux; \
    wget -qO- https://github.com/startersclan/GeoLiteCity-data/raw/c14d99c42446f586e3ca9c89fe13714474921d65/GeoLiteCity.dat > /GeoLiteCity.dat; \
    wget -qO- https://cdn.jsdelivr.net/npm/geolite2-city@1.0.0/GeoLite2-City.mmdb.gz > /GeoLite2-City.mmdb.gz; \
    gzip -d /GeoLite2-City.mmdb.gz;

COPY ./src/scripts /scripts
RUN set -eux; \
    mv -v /GeoLiteCity.dat /scripts/GeoLiteCity/GeoLiteCity.dat; \
    mv -v /GeoLite2-City.mmdb /scripts/GeoLiteCity/GeoLite2-City.mmdb;

FROM debian:bookworm-slim AS runtime

RUN set -eux; \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        perl \
        libdbi-perl \
        libdbd-mysql-perl \
        libdbd-mariadb-perl \
        libgeoip2-perl \
        libgeo-ip-perl \
        libemail-sender-perl \
        libsyntax-keyword-try-perl \
    ; \
    rm -rf /var/lib/apt/lists/*

COPY --from=build /scripts /scripts

WORKDIR /scripts
EXPOSE 27500/udp
STOPSIGNAL SIGINT
ENTRYPOINT ["perl", "./hlstats.pl"]

FROM runtime AS dev

RUN set -eux; \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        cron \
        curl \
        openssl \
        procps \
        wget \
    ; \
    rm -rf /var/lib/apt/lists/*

FROM runtime AS prod
