FROM alpine:latest AS build

RUN set -eux; \
    # Download the GeoIP binary. Maxmind discontinued distributing the GeoLite Legacy databases. See: https://support.maxmind.com/geolite-legacy-discontinuation-notice/
    # So let's download it from our fork of GeoLiteCity.dat
    wget -qO- https://github.com/startersclan/GeoLiteCity-data/raw/c14d99c42446f586e3ca9c89fe13714474921d65/GeoLiteCity.dat > /GeoLiteCity.dat; \
    # Download the GeoIP2 binary. Maxmind discontinued distributing the GeoLite2 databases publicly, so a license key is needed. See: https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/
    # In order to obtain the secret MAXMIND_LICENSE_KEY, we assume we have a sidecar secrets-server which will serve the secret MAXMIND_LICENSE_KEY at: http://localhost:8000/MAXMIND_LICENSE_KEY
    wget -qO- https://cdn.jsdelivr.net/npm/geolite2-city@1.0.0/GeoLite2-City.mmdb.gz > /GeoLite2-City.mmdb.gz; \
    gzip -d /GeoLite2-City.mmdb.gz;

# Copy scripts and set permissions
COPY ./src/scripts /scripts
RUN set -eux; \
    mv -v /GeoLiteCity.dat /scripts/GeoLiteCity/GeoLiteCity.dat; \
    mv -v /GeoLite2-City.mmdb /scripts/GeoLiteCity/GeoLite2-City.mmdb; \
    find /scripts -type d -exec chmod 750 {} \;; \
    find /scripts -type f -exec chmod 640 {} \;; \
    find /scripts -type f -name '*.sh' -exec chmod 750 {} \;; \
    find /scripts -type f -name '*.pl' -exec chmod 750 {} \;; \
    find /scripts -type f -name 'run_*' -exec chmod 750 {} \;; \
    ls -al /scripts/*

FROM perl:5.38.0-slim-bookworm AS dev

# Install modules
RUN set -eux; \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        build-essential \
        default-libmysqlclient-dev; \
    \
    cpanm DBI; \
    \
    cpanm --notest DBD::mysql; \
    \
    cpanm Geo::IP::PurePerl; \
    cpanm GeoIP2::Database::Reader; \
    cpanm MaxMind::DB::Reader; \
    cpanm Syntax::Keyword::Try; \
    \
    # Optional modules: Email
    cpanm Email::Sender::Simple; \
    apt-get purge --auto-remove -y build-essential; \
    rm -rf /var/lib/apt/lists/* /root/.cpan/ /root/.cpanm/

# Install tools
RUN set -eux; \
    apt-get update; \
    apt-get install -y \
        procps \
        # Cron tools
        cron \
        curl \
        wget \
        openssl \
    && rm -rf /var/lib/apt/lists/*

COPY --from=build /scripts /scripts

WORKDIR /scripts

EXPOSE 27500/udp

STOPSIGNAL SIGINT

ENTRYPOINT ["perl", "./hlstats.pl"]

FROM dev AS prod
